#pragma once
// AI-powered dialog + TTS voice on skinned NPCs (X3_WORLD_BLUEPRINT §3
// "AI-powered dialog": "3 selectable in-game modes — scripted trees / live
// Claude+Grok / hybrid ... built mode-agnostic").
//
// Game/slice code only — engine/ stays pure. This module depends only on the
// engine's app-facing audio interface (IAudioSystem, to PLAY a TTS clip) + plain
// PODs/std + a tiny read-only "speaking NPC" seam. It NEVER opens a socket, NEVER
// embeds an API key, and NEVER links an HTTP/AI client. The two cloud-facing
// capabilities (a Claude/Grok text provider, a realistic-voice TTS vendor) are
// INJECTED by the HOST as std::function callbacks (the same host-hook pattern as
// app/cues.h GameCueFn and monster.h BossPhaseFn). With NO hooks set the system
// is fully offline + deterministic: the authored dialogue TREE is the guaranteed
// path. This is what keeps the ENGINE offline-safe while letting Tim wire a live
// provider + a voice vendor purely in host config later.
//
// THE THREE BLUEPRINT MODES (player-selectable, all served by ONE code path):
//   * Tree   — scripted authored nodes only (the "boring" floor; ALWAYS works,
//              NO network, deterministic). The guaranteed baseline.
//   * Ai      — when the host has injected an AiProviderFn, an NPC line may be
//              GENERATED by the provider (host calls Claude/Grok) using the
//              DialogContext (speaker, history, player choice). If the provider
//              is absent OR returns empty, it FALLS BACK to the authored line.
//   * Hybrid  — authored structure + choices, but each NPC line is run through
//              the provider when present (provider "rewrites" the authored line
//              in-character); identical fallback to the tree when absent.
// Selecting Ai/Hybrid WITHOUT a provider hook behaves exactly like Tree — there
// is no failure path that requires a network.
//
// VOICE (optional): when the host injects a TtsProviderFn, each NPC line that
// plays requests an AudioClip from the vendor and plays it through the existing
// miniaudio IAudioSystem. With no TTS hook the line is silent text (subtitle
// only). The NPC enters a SPEAKING state for the duration of the line (a talk
// pose / head-bob driven through the read-only anim Skinner via the ISpeakingNpc
// seam) and exits when the clip / line timer ends. Lip-sync is NOT required.
//
// STEADY-STATE: no per-frame heap allocation. The tree + node text are built once
// at authoring time; advancing a line copies small fixed strings into reused
// members; the per-frame update() only ticks a timer + (optionally) nudges the
// speaking pose. AI/TTS hooks fire ONCE per line (on the line starting), never per
// frame.

#include "engine/audio/IAudioSystem.h"   // IAudioSystem (PLAY the TTS clip)

#include <cstdint>
#include <functional>
#include <string>
#include <string_view>
#include <vector>

namespace x3::dialog {

// ===========================================================================
// Voices + clips.
// ===========================================================================

// A stable per-character voice id the TTS vendor maps to a specific synthesized
// voice (Sarah's voice, K'thara's voice, ...). New characters append at the end
// (stable numeric values so a save/host-config never shifts). The vendor mapping
// (which value -> which cloud voice) is HOST config — the engine only passes the id.
enum class VoiceId : uint32_t {
    Narrator = 0,   // neutral system / narration voice
    Sarah    = 1,   // EFLZ hacker ally
    Kthara   = 2,   // Salvari mentor (K'thara)
    Jake     = 3,   // the player character (Subject 7-Alpha)
    Count    = 4
};

// Human-readable voice name (logs / the self-test trace / a future config UI).
const char* voiceName(VoiceId v);

// An audio clip handed back by the TTS vendor. POD: the vendor either (a) returns
// a path to a synthesized file on disk for the engine to load+play, or (b) hands
// over decoded PCM samples directly. The engine plays whichever is populated:
//   * If `path` is non-empty, the engine loads + plays it via IAudioSystem.
//   * Else if `samples` is non-empty, the engine plays the raw PCM (a host helper
//     wires it through the audio system — for the stub/test path the bytes are
//     just measured, never decoded).
// `durationSec` is the clip length the speaking-state timer uses; when 0 the
// engine estimates a duration from the line length (so subtitles still pace even
// for a silent / unknown-length clip). An EMPTY clip (no path, no samples,
// duration 0) means "the vendor declined / failed" -> the line is silent text.
struct AudioClip {
    std::string          path;                // absolute file path to play, or empty
    std::vector<int16_t> samples;             // OR raw interleaved PCM, or empty
    uint32_t             sampleRate = 48000;  // PCM sample rate (Hz) when samples used
    uint32_t             channels   = 1;      // PCM channel count when samples used
    float                durationSec = 0.0f;  // clip length (s); 0 => estimate from text

    bool empty() const { return path.empty() && samples.empty(); }
};

// ===========================================================================
// Injectable HOST hooks (the offline-safe seam — see the file header).
// ===========================================================================

// Conversation context handed to the AI provider when it generates / rewrites an
// NPC line. Pure data the host serializes into its Claude/Grok prompt. No engine
// types leak in; the host owns the actual network call + prompt. Passed by const&
// (the provider must not retain pointers past the call).
struct DialogContext {
    std::string_view speaker;        // the NPC's display name ("Sarah", "K'thara")
    VoiceId          voice = VoiceId::Narrator;
    std::string_view authoredLine;   // the tree's authored line for this node (the
                                     //   fallback + the "rewrite this in-character"
                                     //   seed for Hybrid mode)
    std::string_view playerChoice;   // the choice text the player just picked to
                                     //   reach this node ("" at the root)
    // Recent conversation history (oldest..newest), "Name: line" formatted, so the
    // provider has short-term memory. Bounded (kHistoryMax) — never grows unbounded.
    const std::vector<std::string>* history = nullptr;
    int32_t          nodeId = -1;    // the authored node id (for host-side caching)
};

// The AI provider hook: given the context, return the NPC's spoken line. The HOST
// implementation may call Claude / Grok (or anything). Returning an EMPTY string
// (or never setting the hook) makes the system fall back to the authored line —
// so a network hiccup / rate-limit / no-key degrades gracefully to the tree. The
// engine calls this AT MOST ONCE per NPC line (when the line starts), NEVER per
// frame, and only when the active mode is Ai or Hybrid.
using AiProviderFn = std::function<std::string(const DialogContext& ctx)>;

// The TTS voice hook: given a finished line + the speaker's voice, return an
// AudioClip to play. The HOST implementation calls a realistic-human-voice vendor.
// Returning an EMPTY clip (or never setting the hook) makes the line silent text.
// Called AT MOST ONCE per NPC line (when the line starts), NEVER per frame.
using TtsProviderFn = std::function<AudioClip(const std::string& line, VoiceId voice)>;

// ===========================================================================
// The read-only SPEAKING-NPC seam (wire dialog to a skinned NPC, requirement 4).
// ===========================================================================
// dialog never depends on MonsterSystem / the renderer directly. Instead the host
// supplies an ISpeakingNpc the dialog drives when a line plays: enter the speaking
// state (start a talk pose / head bob via the existing anim Skinner — READ-only
// use), get nudged each frame while speaking (so a talk-bob can advance), and exit
// when the line ends. A null speaker means "subtitle-only, no NPC animation"
// (e.g. a headless line or a narrator). The host's concrete implementation reads
// the NPC's Skinner; the dialog system only calls these three verbs.
class ISpeakingNpc {
public:
    virtual ~ISpeakingNpc() = default;

    // Enter the SPEAKING state: start a talk animation / head motion for `line`
    // spoken with `voice`. Called once when a line begins. The implementation
    // typically triggers a "talk" clip / head-bob on its Skinner and shows the
    // line as a subtitle. `estDurationSec` is the line's expected length so the
    // animation can pace itself (a clip's real length when TTS provided one).
    virtual void beginSpeaking(std::string_view line, VoiceId voice,
                               float estDurationSec) = 0;

    // Per-frame nudge while speaking: advance the talk pose / head bob by `dt`.
    // Cheap; no allocation. `phase01` runs 0..1 across the line so the mouth/head
    // motion can ramp in + settle out. Called every update() while a line plays.
    virtual void tickSpeaking(float dt, float phase01) = 0;

    // Exit the SPEAKING state: return to idle. Called once when the line ends
    // (clip/timer elapsed or the line was skipped).
    virtual void endSpeaking() = 0;
};

// ===========================================================================
// Authored dialogue TREE (the offline baseline — requirement 1).
// ===========================================================================

// One selectable player choice at a node: the text shown to the player + the node
// id it jumps to (kEndNode ends the conversation). Authored once.
struct Choice {
    std::string text;             // what the player sees / picks
    int32_t     nextNode = -1;    // target node id (kEndNode = end)
};

// A conversation node: the NPC speaks `line` (the authored fallback / AI seed),
// then the player picks one of `choices`. A node with no choices is terminal once
// its line has been delivered (the conversation ends). Authored once.
struct Node {
    int32_t          id = -1;        // unique within the tree
    std::string      speaker;        // display name ("Sarah", "K'thara")
    VoiceId          voice = VoiceId::Narrator;
    std::string      line;           // the authored NPC line for this node
    std::vector<Choice> choices;     // player choices (empty => terminal)
};

// Sentinel node ids.
constexpr int32_t kEndNode  = -1;    // a choice that ends the conversation
constexpr int32_t kNoNode   = -2;    // "no current node" (conversation inactive)

// Max conversation-history lines kept for the AI context (bounded — the steady
// path never grows the history vector past this; oldest lines drop off).
constexpr uint32_t kHistoryMax = 12;

// The three blueprint dialog modes (player-selectable, see the file header).
enum class Mode : uint32_t { Tree = 0, Ai = 1, Hybrid = 2 };
const char* modeName(Mode m);

// A built conversation tree: an ordered set of nodes + the entry node id. Built
// once (authoring), then handed to the DialogSystem to run. nodeById() resolves a
// node id to its node (nullptr if absent / sentinel).
struct Tree {
    std::vector<Node> nodes;
    int32_t           startNode = -1;

    const Node* nodeById(int32_t id) const;
    // Validate the tree: every choice target is a real node or kEndNode, the start
    // node exists, ids are unique. Returns true if sound. Logs the first problem.
    bool validate() const;
};

// ---------------------------------------------------------------------------
// Sample authored trees (offline content — Sarah + K'thara, per the TASK). These
// are the guaranteed-offline baseline lines the blueprint calls for.
// ---------------------------------------------------------------------------
// Sarah (EFLZ hacker ally): the F1 "wake up / escape" briefing branch.
Tree sampleSarahTree();
// K'thara (Salvari mentor): the Act-2 "first contact / trust" branch.
Tree sampleKtharaTree();

// ===========================================================================
// The pluggable dialog system (IDialogSystem).
// ===========================================================================
// The single interface the host drives. The concrete DialogSystem below is the
// only implementation; the abstract base documents the contract + keeps the host
// decoupled (and mirrors the engine's IAudioSystem / INavGrid factory style).
class IDialogSystem {
public:
    virtual ~IDialogSystem() = default;

    // ---- One-time wiring (all OPTIONAL; unset => offline-safe defaults) ----
    // Inject the AI text provider (Claude/Grok). Unset => Tree fallback always.
    virtual void setAiProvider(AiProviderFn fn) = 0;
    // Inject the TTS voice vendor. Unset => silent text (subtitle only).
    virtual void setTtsProvider(TtsProviderFn fn) = 0;
    // Borrow the engine audio system to PLAY a TTS clip's `path`. May be null
    // (headless / no audio) — then a path-based clip is treated as silent (its
    // duration still paces the subtitle). The dialog system does not own it.
    virtual void setAudioSystem(x3::audio::IAudioSystem* audio) = 0;
    // Borrow the speaking NPC the running conversation animates. May be null
    // (subtitle-only). Borrowed, not owned.
    virtual void setSpeakingNpc(ISpeakingNpc* npc) = 0;
    // Select the dialog mode (Tree / Ai / Hybrid). Default Tree.
    virtual void setMode(Mode mode) = 0;
    virtual Mode mode() const = 0;

    // ---- Run a conversation ----
    // Start `tree` from its start node. Resets history + state. Returns false if
    // the tree is invalid (then nothing starts). After start(), the first NPC line
    // is delivered (provider/TTS fired, speaking state entered) on this call.
    virtual bool start(const Tree& tree) = 0;

    // Is a conversation currently running?
    virtual bool active() const = 0;

    // The current NPC line being shown (the subtitle text). Empty when inactive.
    virtual std::string_view currentLine() const = 0;
    // The current speaker display name. Empty when inactive.
    virtual std::string_view currentSpeaker() const = 0;
    // True while the NPC is mid-line (speaking-state active / timer running). The
    // player choices are intended to show once this goes false (line finished).
    virtual bool speaking() const = 0;

    // The choices available at the current node (empty while still speaking, or at
    // a terminal node). The host renders these + calls choose() with an index.
    virtual const std::vector<Choice>& choices() const = 0;

    // Pick choice `index` (into choices()). Advances to the target node and
    // delivers its NPC line (provider/TTS fired, speaking entered). A choice whose
    // target is kEndNode ends the conversation (active() -> false). Out-of-range
    // index or "still speaking" => ignored (returns false). Returns true if it
    // advanced/ended.
    virtual bool choose(uint32_t index) = 0;

    // Skip the rest of the current line immediately (the player pressed "skip"):
    // stop any clip, exit the speaking state, reveal the choices now. No-op if not
    // speaking.
    virtual void skip() = 0;

    // Per-frame tick: advance the speaking-state timer; when the line's clip /
    // estimated duration elapses, exit the speaking state (so choices reveal). Also
    // nudges the speaking NPC's talk pose. Cheap; no steady-state allocation.
    virtual void update(float dt) = 0;

    // ---- Diagnostics (for the HUD / self-test) ----
    // Number of NPC lines delivered so far this conversation (advances per node).
    virtual uint32_t linesDelivered() const = 0;
    // Was the LAST delivered line produced by the AI provider (true) or the authored
    // tree (false)? Lets the test assert provider-vs-fallback selection.
    virtual bool lastLineFromProvider() const = 0;
    // Did the LAST delivered line get a (non-empty) TTS clip + play it? Lets the
    // test assert the TTS request + the NPC speaking-state entry.
    virtual bool lastLineHadVoice() const = 0;
};

// Factory: a fresh, offline-safe dialog system (Tree mode, no hooks).
IDialogSystem* createDialogSystem();

// ===========================================================================
// Headless self-test (--test-dialog). Fully offline with STUB hooks. Asserts:
//   * the tree advances through nodes + player-choice branches deterministically;
//   * with a stub AI provider set, lines come FROM the provider; WITHOUT it (and
//     in Tree mode) lines fall back to the authored tree; an empty-returning
//     provider also falls back;
//   * with a stub TTS hook set, a clip is requested + the NPC enters/exits the
//     SPEAKING state across the line; without it the line is silent (no speaking
//     clip, subtitle still shown);
//   * no network is required anywhere (the hooks are pure local stubs) and the run
//     is leak-clean (no leaked nodes/handles).
// Prints "dialog: X/Y passed"; returns true iff all pass. No window / Vulkan / net.
// ===========================================================================
bool runDialogSelfTest();

} // namespace x3::dialog
