# Embed a TTF as a C byte array so a HUD/menu font can ship inside the single
# binary (zero external-file dependency — the embedded blob is the bake source /
# guaranteed fallback).
#
# DEFAULT (no args): regenerate engine/rhi/font_robotomono.h from
#   assets/fonts/RobotoMono-Regular.ttf  (the universal embedded fallback).
#     pwsh -File tools/embed_font.ps1
#
# EMBED A ROLE FONT (single-binary ship): point it at any role's .ttf and give a
# C symbol + output header. Example — bake Orbitron-Bold (the Title role) in:
#     pwsh -File tools/embed_font.ps1 `
#         -Src    assets/fonts/Orbitron/static/Orbitron-Bold.ttf `
#         -Symbol kOrbitronBoldTTF `
#         -Out    engine/rhi/font_orbitron.h
# Then, in engine/rhi/VulkanRenderDevice.cpp:
#   1. #include "font_orbitron.h" near font_robotomono.h.
#   2. In buildFontAtlas(), for that role set ttf/ttfSize to the embedded blob
#      (kOrbitronBoldTTF / kOrbitronBoldTTFSize) instead of the assets/ file load
#      (mirror the kRobotoMonoTTF usage). The assets/fonts/ runtime-load can stay
#      as a drop-in override or be removed for a fully self-contained ship.
param(
    [string]$Src    = '',
    [string]$Symbol = 'kRobotoMonoTTF',
    [string]$Out    = ''
)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($Src)) { $Src = Join-Path $root 'assets/fonts/RobotoMono-Regular.ttf' }
elseif (-not [System.IO.Path]::IsPathRooted($Src)) { $Src = Join-Path $root $Src }
if ([string]::IsNullOrWhiteSpace($Out)) { $Out = Join-Path $root 'engine/rhi/font_robotomono.h' }
elseif (-not [System.IO.Path]::IsPathRooted($Out)) { $Out = Join-Path $root $Out }
if (-not (Test-Path $Src)) { throw "font not found: $Src" }

$bytes = [System.IO.File]::ReadAllBytes($Src)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/embed_font.ps1 -- do not edit by hand.")
[void]$sb.AppendLine("// Embedded TTF: $([System.IO.Path]::GetFileName($Src)).")
[void]$sb.AppendLine("// Baked into a HUD/menu glyph atlas via stb_truetype at device init.")
[void]$sb.AppendLine("// Regenerate with tools/embed_font.ps1 if the .ttf is replaced.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstddef>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace x3::rhi {")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("inline const unsigned char $Symbol[] = {")
$line = New-Object System.Text.StringBuilder
for ($i = 0; $i -lt $bytes.Length; $i++) {
    [void]$line.Append($bytes[$i]); [void]$line.Append(',')
    if ((($i + 1) % 20) -eq 0) { [void]$sb.AppendLine($line.ToString()); $line.Clear() | Out-Null }
}
if ($line.Length -gt 0) { [void]$sb.AppendLine($line.ToString()) }
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("inline const size_t ${Symbol}Size = sizeof($Symbol);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace x3::rhi")
[System.IO.File]::WriteAllText($Out, $sb.ToString())
Write-Output ("Wrote $Out (symbol $Symbol, " + $bytes.Length + " font bytes)")
